version: 1.2
enable: true            # Global enable toggle for the plugin
ignore_animals: true    # If true, the plugin does not prevent animals from spawning
min_height: 50          # Allows all spawns to happen below this height
scanners:
    main:
      enable: true      # Activate this scanner (default true)
      action: prevent   # Action to perform on detection: prevent / allow
      priority: 0       # Higher priority scanners are run first (default 1)
      range: 15         # Size of the detection square measured around the spawning block (default 5)
      below: 5          # Number of blocks below the spawn position (default 2)
      above: 5          # Number of blocks above the spawn position (default 2)
      count: 10         # Number of blocks matched after which the action is performed (default 1)
      hard_limit: 50    # Hard limit of detected blocks after which the action is performed
      block_types:      # List of blocks that will be used to trigger the action (at least 1 required)
      - WOOD
      - COBBLESTONE
      - DIAMOND_BLOCK
      - BRICK
      - FENCE
      - GOLD_BLOCK
      - IRON_BLOCK
      - LAPIS_BLOCK
      - SNOW_BLOCK
      - COBBLESTONE_STAIRS
      - WOOD_STAIRS
      - WOODEN_DOOR
      - IRON_DOOR
      - STEP
      - DOUBLE_STEP
      - WOOL
      - BED_BLOCK
      - CHEST
      - FENCE_GATE
      - MOSSY_COBBLESTONE
      - SMOOTH_BRICK
      - SMOOTH_STAIRS
      - THIN_GLASS
      - TRAP_DOOR
      - OBSIDIAN
      - BEDROCK
      - IRON_DOOR_BLOCK
      - IRON_FENCE
      - NETHER_BRICK
      - NETHER_FENCE
      structures:       # Structure detection (defaults to optimized no-op path)
        range: 5        # Same as scanner range (default 0)
        below: 2        # Same as scanner below (default 0)
        above: 2        # Same as scanner above (default 0)
        count: 3        # Same as scanner count (default 1)
    treetops:           # Treetop scanner
      action: prevent
      count: 4
      above: 1
      block_types: LEAF
    spawners:           # Spawns near a spawner or cobweb
      action: allow
      block_types: [ MOB_SPAWNER, COBWEB ]
