enable: true          # Global enable toggle for the plugin
ignore_animals: true  # If true, the plugin does not prevent animals from spawning
detect:       # Detection-specitic settings
  radius: 15        # Size of the detection square measured around the spawning block
  height: 5         # Vertical size of the detection box, both above and below the spawn
  limit: 10         # Number of blocks matched after which the spawning is disallowed
  depth_limit: 50   # Allows all spawns to happen below this height
  hard_limit: 500   # Hard limit of detected blocks after which the spawn is disallowed
  block_types:      # List of blocks that will be used to detect man-made structures
  - WOOD
  - COBBLESTONE
  - DIAMOND_BLOCK
  - BRICK
  - FENCE
  - GOLD_BLOCK
  - IRON_BLOCK
  - LAPIS_BLOCK
  - SNOW_BLOCK
  - COBBLESTONE_STAIRS
  - WOOD_STAIRS
  - WOODEN_DOOR
  - IRON_DOOR
  - STEP
  - DOUBLE_STEP
  - WOOL
  - BED_BLOCK
  - CHEST
  - FENCE_GATE
  - MOSSY_COBBLESTONE
  - SMOOTH_BRICK
  - SMOOTH_STAIRS
  - THIN_GLASS
  - TRAP_DOOR
  - OBSIDIAN
  - BEDROCK
  - IRON_DOOR_BLOCK
  - IRON_FENCE
  - NETHER_BRICK
  - NETHER_FENCE
structures: # Structure detection settings
  detect: true
  radius: 5
  height: 2
  limit: 3
treetops:   # Treetop spawn prevention
  allow: false
  minimum_leaves: 4
spawners:   # Spawns near a spawner
  allow: true
cobwebs:    # Spawns near a cobweb
  allow: true
  limit: 1  # Number of cobweb blocks required to allow the spawn
