name: NotOnMyLawn
main: net.gigaherz.NotOnMyLawn.BukkitPlugin
version: 1.1
commands:
   notonmylawn:
     aliases: noml
     description: Used to show or change settings for NotOnMyLawn.
     usage: |
       Usage:
       /<command> reload
       /<command> enable
       /<command> disable
       /<command> show <config name>
       /<command> set <config name> <value>
       Note: <config name> corresponds to the config.yml key path, separated by '.'
       Example: /<command> set cobwebs.allow false
     permission: notonmylawn.config
     permission-message: You need permission '<permission>' to use this command.
permissions:
  notonmylawn.config:
    default: op
